// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMsNOJbfp_J7dKmD4bmvT8RlHq7OOkQYM',
    appId: '1:96744850313:web:053ce5eada0dd3e4dfd758',
    messagingSenderId: '96744850313',
    projectId: 'mychef-3ef78',
    authDomain: 'mychef-3ef78.firebaseapp.com',
    databaseURL: 'https://mychef-3ef78-default-rtdb.firebaseio.com',
    storageBucket: 'mychef-3ef78.appspot.com',
    measurementId: 'G-ME6LEGBZ2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Gc9uVvNDHxZUXyykc7WgohvMltFh1yQ',
    appId: '1:96744850313:android:14decb4aa0e5a133dfd758',
    messagingSenderId: '96744850313',
    projectId: 'mychef-3ef78',
    databaseURL: 'https://mychef-3ef78-default-rtdb.firebaseio.com',
    storageBucket: 'mychef-3ef78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpBS3AARft_sFJ8KRjzziKztEoNf-F7Qg',
    appId: '1:96744850313:ios:8eb6c072fca3d2acdfd758',
    messagingSenderId: '96744850313',
    projectId: 'mychef-3ef78',
    databaseURL: 'https://mychef-3ef78-default-rtdb.firebaseio.com',
    storageBucket: 'mychef-3ef78.appspot.com',
    iosBundleId: 'com.example.chef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpBS3AARft_sFJ8KRjzziKztEoNf-F7Qg',
    appId: '1:96744850313:ios:2566c34889bc8718dfd758',
    messagingSenderId: '96744850313',
    projectId: 'mychef-3ef78',
    databaseURL: 'https://mychef-3ef78-default-rtdb.firebaseio.com',
    storageBucket: 'mychef-3ef78.appspot.com',
    iosBundleId: 'com.example.chef.RunnerTests',
  );
}
